name: sdg
baseurl: sdg
excerpt_separator: <excerpt>

permalink: /:year/:month/:day/:title
plugins:
  - jekyll-seo-tag
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "page"
